/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'h.aydogdu' at '14-10-16 21:22' with Gradle 2.14.1
 *
 * @author h.aydogdu, @date 14-10-16 21:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
